### 주민 등록
POST /residents
Host: localhost:8080
Content-Type: application/json

{
"name": "apiTest",
"residentRegistrationNumber":"123456-78910",
"genderCode":"M",
"birthDate": "2023-01-01 10:30:00",
"birthPlaceCode":"ABED",
"registrationBaseAddress":"대왕판교로645"
}

### 주민 수정
PUT /residents/8
Host: localhost:8080
Content-Type: application/json

{
  "name": "apiTestUpdate",
  "genderCode":"남",
  "registrationBaseAddress":"대왕판교로645Update"
}















### 출생신고서 등록
POST /residents/{serialNumber}/birth

### 출생신고서 수정
PUT /residents/{serialNumber}/birth/{targetSerialNumber}

### 출생신고서 삭제
DELETE /residents/{serialNumber}/birth/{targetSerialNumber}

### 사망신고서 등록
POST /residents/{serialNumber}/death

### 사망신고서 수정
PUT /residents/{serialNumber}/death/{targetSerialNumber}

### 사망신고서 삭제
DELETE /residents/{serialNumber}/death/{targetSerialNumber}

### 세대 등록
POST /household

### 세대 삭제
DELETE /household/{householdSerialNumber}
