### 주민 등록
POST /residents
Host: localhost:8080
Content-Type: application/json

{
"name": "apiTest",
"residentRegistrationNumber":"123456-78910",
"genderCode":"M",
"birthDate": "2023-01-01 10:30:00",
"birthPlaceCode":"ABED",
"registrationBaseAddress":"대왕판교로645"
}

### 주민 수정
PUT /residents/8
Host: localhost:8080
Content-Type: application/json

{
  "name": "apiTestUpdate",
  "genderCode":"남",
  "registrationBaseAddress":"대왕판교로645Update"
}
